apiVersion: v1
kind: Service
metadata:
  name: jaeger-query-clusterip
  namespace: default
spec:
  selector:
    app.kubernetes.io/name: jaeger
  ports:
    - name: http-query
      port: 16686
      targetPort: 16686
      protocol: TCP
    - name: http-collector
      port: 14268
      targetPort: 14268
      protocol: TCP
