// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0--rc1
// source: api/follow/v1/follow.proto

package followv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    uint64                 `protobuf:"varint,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	FolloweeId    uint64                 `protobuf:"varint,2,opt,name=followee_id,json=followeeId,proto3" json:"followee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowRequest) Reset() {
	*x = FollowRequest{}
	mi := &file_api_follow_v1_follow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowRequest) ProtoMessage() {}

func (x *FollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_follow_v1_follow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowRequest.ProtoReflect.Descriptor instead.
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return file_api_follow_v1_follow_proto_rawDescGZIP(), []int{0}
}

func (x *FollowRequest) GetFollowerId() uint64 {
	if x != nil {
		return x.FollowerId
	}
	return 0
}

func (x *FollowRequest) GetFolloweeId() uint64 {
	if x != nil {
		return x.FolloweeId
	}
	return 0
}

type FollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowResponse) Reset() {
	*x = FollowResponse{}
	mi := &file_api_follow_v1_follow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowResponse) ProtoMessage() {}

func (x *FollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_follow_v1_follow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowResponse.ProtoReflect.Descriptor instead.
func (*FollowResponse) Descriptor() ([]byte, []int) {
	return file_api_follow_v1_follow_proto_rawDescGZIP(), []int{1}
}

func (x *FollowResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnfollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    uint64                 `protobuf:"varint,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	FolloweeId    uint64                 `protobuf:"varint,2,opt,name=followee_id,json=followeeId,proto3" json:"followee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowRequest) Reset() {
	*x = UnfollowRequest{}
	mi := &file_api_follow_v1_follow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowRequest) ProtoMessage() {}

func (x *UnfollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_follow_v1_follow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowRequest.ProtoReflect.Descriptor instead.
func (*UnfollowRequest) Descriptor() ([]byte, []int) {
	return file_api_follow_v1_follow_proto_rawDescGZIP(), []int{2}
}

func (x *UnfollowRequest) GetFollowerId() uint64 {
	if x != nil {
		return x.FollowerId
	}
	return 0
}

func (x *UnfollowRequest) GetFolloweeId() uint64 {
	if x != nil {
		return x.FolloweeId
	}
	return 0
}

type UnfollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowResponse) Reset() {
	*x = UnfollowResponse{}
	mi := &file_api_follow_v1_follow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowResponse) ProtoMessage() {}

func (x *UnfollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_follow_v1_follow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowResponse.ProtoReflect.Descriptor instead.
func (*UnfollowResponse) Descriptor() ([]byte, []int) {
	return file_api_follow_v1_follow_proto_rawDescGZIP(), []int{3}
}

func (x *UnfollowResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type IsFollowingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    uint64                 `protobuf:"varint,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	FolloweeId    uint64                 `protobuf:"varint,2,opt,name=followee_id,json=followeeId,proto3" json:"followee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFollowingRequest) Reset() {
	*x = IsFollowingRequest{}
	mi := &file_api_follow_v1_follow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFollowingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFollowingRequest) ProtoMessage() {}

func (x *IsFollowingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_follow_v1_follow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFollowingRequest.ProtoReflect.Descriptor instead.
func (*IsFollowingRequest) Descriptor() ([]byte, []int) {
	return file_api_follow_v1_follow_proto_rawDescGZIP(), []int{4}
}

func (x *IsFollowingRequest) GetFollowerId() uint64 {
	if x != nil {
		return x.FollowerId
	}
	return 0
}

func (x *IsFollowingRequest) GetFolloweeId() uint64 {
	if x != nil {
		return x.FolloweeId
	}
	return 0
}

type IsFollowingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsFollowing   bool                   `protobuf:"varint,1,opt,name=is_following,json=isFollowing,proto3" json:"is_following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFollowingResponse) Reset() {
	*x = IsFollowingResponse{}
	mi := &file_api_follow_v1_follow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFollowingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFollowingResponse) ProtoMessage() {}

func (x *IsFollowingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_follow_v1_follow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFollowingResponse.ProtoReflect.Descriptor instead.
func (*IsFollowingResponse) Descriptor() ([]byte, []int) {
	return file_api_follow_v1_follow_proto_rawDescGZIP(), []int{5}
}

func (x *IsFollowingResponse) GetIsFollowing() bool {
	if x != nil {
		return x.IsFollowing
	}
	return false
}

type GetFollowersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Cursor        uint64                 `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowersRequest) Reset() {
	*x = GetFollowersRequest{}
	mi := &file_api_follow_v1_follow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowersRequest) ProtoMessage() {}

func (x *GetFollowersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_follow_v1_follow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowersRequest.ProtoReflect.Descriptor instead.
func (*GetFollowersRequest) Descriptor() ([]byte, []int) {
	return file_api_follow_v1_follow_proto_rawDescGZIP(), []int{6}
}

func (x *GetFollowersRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFollowersRequest) GetCursor() uint64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *GetFollowersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetFollowersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerIds   []uint64               `protobuf:"varint,1,rep,packed,name=follower_ids,json=followerIds,proto3" json:"follower_ids,omitempty"`
	NextCursor    uint64                 `protobuf:"varint,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowersResponse) Reset() {
	*x = GetFollowersResponse{}
	mi := &file_api_follow_v1_follow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowersResponse) ProtoMessage() {}

func (x *GetFollowersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_follow_v1_follow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowersResponse.ProtoReflect.Descriptor instead.
func (*GetFollowersResponse) Descriptor() ([]byte, []int) {
	return file_api_follow_v1_follow_proto_rawDescGZIP(), []int{7}
}

func (x *GetFollowersResponse) GetFollowerIds() []uint64 {
	if x != nil {
		return x.FollowerIds
	}
	return nil
}

func (x *GetFollowersResponse) GetNextCursor() uint64 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

func (x *GetFollowersResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type GetFolloweesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Cursor        uint64                 `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFolloweesRequest) Reset() {
	*x = GetFolloweesRequest{}
	mi := &file_api_follow_v1_follow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFolloweesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFolloweesRequest) ProtoMessage() {}

func (x *GetFolloweesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_follow_v1_follow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFolloweesRequest.ProtoReflect.Descriptor instead.
func (*GetFolloweesRequest) Descriptor() ([]byte, []int) {
	return file_api_follow_v1_follow_proto_rawDescGZIP(), []int{8}
}

func (x *GetFolloweesRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFolloweesRequest) GetCursor() uint64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *GetFolloweesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetFolloweesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolloweeIds   []uint64               `protobuf:"varint,1,rep,packed,name=followee_ids,json=followeeIds,proto3" json:"followee_ids,omitempty"`
	NextCursor    uint64                 `protobuf:"varint,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFolloweesResponse) Reset() {
	*x = GetFolloweesResponse{}
	mi := &file_api_follow_v1_follow_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFolloweesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFolloweesResponse) ProtoMessage() {}

func (x *GetFolloweesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_follow_v1_follow_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFolloweesResponse.ProtoReflect.Descriptor instead.
func (*GetFolloweesResponse) Descriptor() ([]byte, []int) {
	return file_api_follow_v1_follow_proto_rawDescGZIP(), []int{9}
}

func (x *GetFolloweesResponse) GetFolloweeIds() []uint64 {
	if x != nil {
		return x.FolloweeIds
	}
	return nil
}

func (x *GetFolloweesResponse) GetNextCursor() uint64 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

func (x *GetFolloweesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type GetFollowStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowStatsRequest) Reset() {
	*x = GetFollowStatsRequest{}
	mi := &file_api_follow_v1_follow_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowStatsRequest) ProtoMessage() {}

func (x *GetFollowStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_follow_v1_follow_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowStatsRequest.ProtoReflect.Descriptor instead.
func (*GetFollowStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_follow_v1_follow_proto_rawDescGZIP(), []int{10}
}

func (x *GetFollowStatsRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetFollowStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerCount int64                  `protobuf:"varint,1,opt,name=follower_count,json=followerCount,proto3" json:"follower_count,omitempty"`
	FolloweeCount int64                  `protobuf:"varint,2,opt,name=followee_count,json=followeeCount,proto3" json:"followee_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowStatsResponse) Reset() {
	*x = GetFollowStatsResponse{}
	mi := &file_api_follow_v1_follow_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowStatsResponse) ProtoMessage() {}

func (x *GetFollowStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_follow_v1_follow_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowStatsResponse.ProtoReflect.Descriptor instead.
func (*GetFollowStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_follow_v1_follow_proto_rawDescGZIP(), []int{11}
}

func (x *GetFollowStatsResponse) GetFollowerCount() int64 {
	if x != nil {
		return x.FollowerCount
	}
	return 0
}

func (x *GetFollowStatsResponse) GetFolloweeCount() int64 {
	if x != nil {
		return x.FolloweeCount
	}
	return 0
}

var File_api_follow_v1_follow_proto protoreflect.FileDescriptor

const file_api_follow_v1_follow_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/follow/v1/follow.proto\x12\tfollow.v1\"Q\n" +
	"\rFollowRequest\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\x04R\n" +
	"followerId\x12\x1f\n" +
	"\vfollowee_id\x18\x02 \x01(\x04R\n" +
	"followeeId\"*\n" +
	"\x0eFollowResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"S\n" +
	"\x0fUnfollowRequest\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\x04R\n" +
	"followerId\x12\x1f\n" +
	"\vfollowee_id\x18\x02 \x01(\x04R\n" +
	"followeeId\",\n" +
	"\x10UnfollowResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"V\n" +
	"\x12IsFollowingRequest\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\x04R\n" +
	"followerId\x12\x1f\n" +
	"\vfollowee_id\x18\x02 \x01(\x04R\n" +
	"followeeId\"8\n" +
	"\x13IsFollowingResponse\x12!\n" +
	"\fis_following\x18\x01 \x01(\bR\visFollowing\"\\\n" +
	"\x13GetFollowersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x04R\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"u\n" +
	"\x14GetFollowersResponse\x12!\n" +
	"\ffollower_ids\x18\x01 \x03(\x04R\vfollowerIds\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\x04R\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"\\\n" +
	"\x13GetFolloweesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x04R\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"u\n" +
	"\x14GetFolloweesResponse\x12!\n" +
	"\ffollowee_ids\x18\x01 \x03(\x04R\vfolloweeIds\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\x04R\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"0\n" +
	"\x15GetFollowStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"f\n" +
	"\x16GetFollowStatsResponse\x12%\n" +
	"\x0efollower_count\x18\x01 \x01(\x03R\rfollowerCount\x12%\n" +
	"\x0efollowee_count\x18\x02 \x01(\x03R\rfolloweeCount2\xda\x03\n" +
	"\rFollowService\x12=\n" +
	"\x06Follow\x12\x18.follow.v1.FollowRequest\x1a\x19.follow.v1.FollowResponse\x12C\n" +
	"\bUnfollow\x12\x1a.follow.v1.UnfollowRequest\x1a\x1b.follow.v1.UnfollowResponse\x12L\n" +
	"\vIsFollowing\x12\x1d.follow.v1.IsFollowingRequest\x1a\x1e.follow.v1.IsFollowingResponse\x12O\n" +
	"\fGetFollowers\x12\x1e.follow.v1.GetFollowersRequest\x1a\x1f.follow.v1.GetFollowersResponse\x12O\n" +
	"\fGetFollowees\x12\x1e.follow.v1.GetFolloweesRequest\x1a\x1f.follow.v1.GetFolloweesResponse\x12U\n" +
	"\x0eGetFollowStats\x12 .follow.v1.GetFollowStatsRequest\x1a!.follow.v1.GetFollowStatsResponseB&Z$twitter-clone/api/follow/v1;followv1b\x06proto3"

var (
	file_api_follow_v1_follow_proto_rawDescOnce sync.Once
	file_api_follow_v1_follow_proto_rawDescData []byte
)

func file_api_follow_v1_follow_proto_rawDescGZIP() []byte {
	file_api_follow_v1_follow_proto_rawDescOnce.Do(func() {
		file_api_follow_v1_follow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_follow_v1_follow_proto_rawDesc), len(file_api_follow_v1_follow_proto_rawDesc)))
	})
	return file_api_follow_v1_follow_proto_rawDescData
}

var file_api_follow_v1_follow_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_follow_v1_follow_proto_goTypes = []any{
	(*FollowRequest)(nil),          // 0: follow.v1.FollowRequest
	(*FollowResponse)(nil),         // 1: follow.v1.FollowResponse
	(*UnfollowRequest)(nil),        // 2: follow.v1.UnfollowRequest
	(*UnfollowResponse)(nil),       // 3: follow.v1.UnfollowResponse
	(*IsFollowingRequest)(nil),     // 4: follow.v1.IsFollowingRequest
	(*IsFollowingResponse)(nil),    // 5: follow.v1.IsFollowingResponse
	(*GetFollowersRequest)(nil),    // 6: follow.v1.GetFollowersRequest
	(*GetFollowersResponse)(nil),   // 7: follow.v1.GetFollowersResponse
	(*GetFolloweesRequest)(nil),    // 8: follow.v1.GetFolloweesRequest
	(*GetFolloweesResponse)(nil),   // 9: follow.v1.GetFolloweesResponse
	(*GetFollowStatsRequest)(nil),  // 10: follow.v1.GetFollowStatsRequest
	(*GetFollowStatsResponse)(nil), // 11: follow.v1.GetFollowStatsResponse
}
var file_api_follow_v1_follow_proto_depIdxs = []int32{
	0,  // 0: follow.v1.FollowService.Follow:input_type -> follow.v1.FollowRequest
	2,  // 1: follow.v1.FollowService.Unfollow:input_type -> follow.v1.UnfollowRequest
	4,  // 2: follow.v1.FollowService.IsFollowing:input_type -> follow.v1.IsFollowingRequest
	6,  // 3: follow.v1.FollowService.GetFollowers:input_type -> follow.v1.GetFollowersRequest
	8,  // 4: follow.v1.FollowService.GetFollowees:input_type -> follow.v1.GetFolloweesRequest
	10, // 5: follow.v1.FollowService.GetFollowStats:input_type -> follow.v1.GetFollowStatsRequest
	1,  // 6: follow.v1.FollowService.Follow:output_type -> follow.v1.FollowResponse
	3,  // 7: follow.v1.FollowService.Unfollow:output_type -> follow.v1.UnfollowResponse
	5,  // 8: follow.v1.FollowService.IsFollowing:output_type -> follow.v1.IsFollowingResponse
	7,  // 9: follow.v1.FollowService.GetFollowers:output_type -> follow.v1.GetFollowersResponse
	9,  // 10: follow.v1.FollowService.GetFollowees:output_type -> follow.v1.GetFolloweesResponse
	11, // 11: follow.v1.FollowService.GetFollowStats:output_type -> follow.v1.GetFollowStatsResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_follow_v1_follow_proto_init() }
func file_api_follow_v1_follow_proto_init() {
	if File_api_follow_v1_follow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_follow_v1_follow_proto_rawDesc), len(file_api_follow_v1_follow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_follow_v1_follow_proto_goTypes,
		DependencyIndexes: file_api_follow_v1_follow_proto_depIdxs,
		MessageInfos:      file_api_follow_v1_follow_proto_msgTypes,
	}.Build()
	File_api_follow_v1_follow_proto = out.File
	file_api_follow_v1_follow_proto_goTypes = nil
	file_api_follow_v1_follow_proto_depIdxs = nil
}
