// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0--rc1
// source: api/tweet/v1/tweet.proto

package tweetv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tweet 推文
type Tweet struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          uint64                 `protobuf:"varint,1,opt,name=id,proto3" test_data:"id,omitempty"`
	UserId      uint64                 `protobuf:"varint,2,opt,name=user_id,test_data=userId,proto3" test_data:"user_id,omitempty"`
	Content     string                 `protobuf:"bytes,3,opt,name=content,proto3" test_data:"content,omitempty"`
	MediaUrls   []string               `protobuf:"bytes,4,rep,name=media_urls,test_data=mediaUrls,proto3" test_data:"media_urls,omitempty"`
	Type        int32                  `protobuf:"varint,5,opt,name=type,proto3" test_data:"type,omitempty"`
	VisibleType int32                  `protobuf:"varint,6,opt,name=visible_type,test_data=visibleType,proto3" test_data:"visible_type,omitempty"`
	CreatedAt   int64                  `protobuf:"varint,7,opt,name=created_at,test_data=createdAt,proto3" test_data:"created_at,omitempty"`
	UpdatedAt   int64                  `protobuf:"varint,8,opt,name=updated_at,test_data=updatedAt,proto3" test_data:"updated_at,omitempty"`
	// 统计数据
	LikeCount     int32 `protobuf:"varint,9,opt,name=like_count,test_data=likeCount,proto3" test_data:"like_count,omitempty"`
	CommentCount  int32 `protobuf:"varint,10,opt,name=comment_count,test_data=commentCount,proto3" test_data:"comment_count,omitempty"`
	ShareCount    int32 `protobuf:"varint,11,opt,name=share_count,test_data=shareCount,proto3" test_data:"share_count,omitempty"`
	IsLiked       bool  `protobuf:"varint,12,opt,name=is_liked,test_data=isLiked,proto3" test_data:"is_liked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tweet) Reset() {
	*x = Tweet{}
	mi := &file_api_tweet_v1_tweet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tweet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tweet) ProtoMessage() {}

func (x *Tweet) ProtoReflect() protoreflect.Message {
	mi := &file_api_tweet_v1_tweet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tweet.ProtoReflect.Descriptor instead.
func (*Tweet) Descriptor() ([]byte, []int) {
	return file_api_tweet_v1_tweet_proto_rawDescGZIP(), []int{0}
}

func (x *Tweet) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tweet) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Tweet) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Tweet) GetMediaUrls() []string {
	if x != nil {
		return x.MediaUrls
	}
	return nil
}

func (x *Tweet) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Tweet) GetVisibleType() int32 {
	if x != nil {
		return x.VisibleType
	}
	return 0
}

func (x *Tweet) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Tweet) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Tweet) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Tweet) GetCommentCount() int32 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *Tweet) GetShareCount() int32 {
	if x != nil {
		return x.ShareCount
	}
	return 0
}

func (x *Tweet) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

type CreateTweetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,test_data=userId,proto3" test_data:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" test_data:"content,omitempty"`
	MediaUrls     []string               `protobuf:"bytes,3,rep,name=media_urls,test_data=mediaUrls,proto3" test_data:"media_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTweetRequest) Reset() {
	*x = CreateTweetRequest{}
	mi := &file_api_tweet_v1_tweet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTweetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTweetRequest) ProtoMessage() {}

func (x *CreateTweetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tweet_v1_tweet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTweetRequest.ProtoReflect.Descriptor instead.
func (*CreateTweetRequest) Descriptor() ([]byte, []int) {
	return file_api_tweet_v1_tweet_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTweetRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateTweetRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateTweetRequest) GetMediaUrls() []string {
	if x != nil {
		return x.MediaUrls
	}
	return nil
}

type CreateTweetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tweet         *Tweet                 `protobuf:"bytes,1,opt,name=tweet,proto3" test_data:"tweet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTweetResponse) Reset() {
	*x = CreateTweetResponse{}
	mi := &file_api_tweet_v1_tweet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTweetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTweetResponse) ProtoMessage() {}

func (x *CreateTweetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tweet_v1_tweet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTweetResponse.ProtoReflect.Descriptor instead.
func (*CreateTweetResponse) Descriptor() ([]byte, []int) {
	return file_api_tweet_v1_tweet_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTweetResponse) GetTweet() *Tweet {
	if x != nil {
		return x.Tweet
	}
	return nil
}

type GetTweetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TweetId       uint64                 `protobuf:"varint,1,opt,name=tweet_id,test_data=tweetId,proto3" test_data:"tweet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTweetRequest) Reset() {
	*x = GetTweetRequest{}
	mi := &file_api_tweet_v1_tweet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTweetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTweetRequest) ProtoMessage() {}

func (x *GetTweetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tweet_v1_tweet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTweetRequest.ProtoReflect.Descriptor instead.
func (*GetTweetRequest) Descriptor() ([]byte, []int) {
	return file_api_tweet_v1_tweet_proto_rawDescGZIP(), []int{3}
}

func (x *GetTweetRequest) GetTweetId() uint64 {
	if x != nil {
		return x.TweetId
	}
	return 0
}

type GetTweetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tweet         *Tweet                 `protobuf:"bytes,1,opt,name=tweet,proto3" test_data:"tweet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTweetResponse) Reset() {
	*x = GetTweetResponse{}
	mi := &file_api_tweet_v1_tweet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTweetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTweetResponse) ProtoMessage() {}

func (x *GetTweetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tweet_v1_tweet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTweetResponse.ProtoReflect.Descriptor instead.
func (*GetTweetResponse) Descriptor() ([]byte, []int) {
	return file_api_tweet_v1_tweet_proto_rawDescGZIP(), []int{4}
}

func (x *GetTweetResponse) GetTweet() *Tweet {
	if x != nil {
		return x.Tweet
	}
	return nil
}

type DeleteTweetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TweetId       uint64                 `protobuf:"varint,1,opt,name=tweet_id,test_data=tweetId,proto3" test_data:"tweet_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,test_data=userId,proto3" test_data:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTweetRequest) Reset() {
	*x = DeleteTweetRequest{}
	mi := &file_api_tweet_v1_tweet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTweetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTweetRequest) ProtoMessage() {}

func (x *DeleteTweetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tweet_v1_tweet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTweetRequest.ProtoReflect.Descriptor instead.
func (*DeleteTweetRequest) Descriptor() ([]byte, []int) {
	return file_api_tweet_v1_tweet_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteTweetRequest) GetTweetId() uint64 {
	if x != nil {
		return x.TweetId
	}
	return 0
}

func (x *DeleteTweetRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteTweetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" test_data:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTweetResponse) Reset() {
	*x = DeleteTweetResponse{}
	mi := &file_api_tweet_v1_tweet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTweetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTweetResponse) ProtoMessage() {}

func (x *DeleteTweetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tweet_v1_tweet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTweetResponse.ProtoReflect.Descriptor instead.
func (*DeleteTweetResponse) Descriptor() ([]byte, []int) {
	return file_api_tweet_v1_tweet_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTweetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetUserTimelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,test_data=userId,proto3" test_data:"user_id,omitempty"`
	Cursor        uint64                 `protobuf:"varint,2,opt,name=cursor,proto3" test_data:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" test_data:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTimelineRequest) Reset() {
	*x = GetUserTimelineRequest{}
	mi := &file_api_tweet_v1_tweet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTimelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTimelineRequest) ProtoMessage() {}

func (x *GetUserTimelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tweet_v1_tweet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTimelineRequest.ProtoReflect.Descriptor instead.
func (*GetUserTimelineRequest) Descriptor() ([]byte, []int) {
	return file_api_tweet_v1_tweet_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserTimelineRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserTimelineRequest) GetCursor() uint64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *GetUserTimelineRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetUserTimelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tweets        []*Tweet               `protobuf:"bytes,1,rep,name=tweets,proto3" test_data:"tweets,omitempty"`
	NextCursor    uint64                 `protobuf:"varint,2,opt,name=next_cursor,test_data=nextCursor,proto3" test_data:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,test_data=hasMore,proto3" test_data:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTimelineResponse) Reset() {
	*x = GetUserTimelineResponse{}
	mi := &file_api_tweet_v1_tweet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTimelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTimelineResponse) ProtoMessage() {}

func (x *GetUserTimelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tweet_v1_tweet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTimelineResponse.ProtoReflect.Descriptor instead.
func (*GetUserTimelineResponse) Descriptor() ([]byte, []int) {
	return file_api_tweet_v1_tweet_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserTimelineResponse) GetTweets() []*Tweet {
	if x != nil {
		return x.Tweets
	}
	return nil
}

func (x *GetUserTimelineResponse) GetNextCursor() uint64 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

func (x *GetUserTimelineResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type GetFeedsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,test_data=userId,proto3" test_data:"user_id,omitempty"`
	Cursor        uint64                 `protobuf:"varint,2,opt,name=cursor,proto3" test_data:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" test_data:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedsRequest) Reset() {
	*x = GetFeedsRequest{}
	mi := &file_api_tweet_v1_tweet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedsRequest) ProtoMessage() {}

func (x *GetFeedsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tweet_v1_tweet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedsRequest.ProtoReflect.Descriptor instead.
func (*GetFeedsRequest) Descriptor() ([]byte, []int) {
	return file_api_tweet_v1_tweet_proto_rawDescGZIP(), []int{9}
}

func (x *GetFeedsRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFeedsRequest) GetCursor() uint64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *GetFeedsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetFeedsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tweets        []*Tweet               `protobuf:"bytes,1,rep,name=tweets,proto3" test_data:"tweets,omitempty"`
	NextCursor    uint64                 `protobuf:"varint,2,opt,name=next_cursor,test_data=nextCursor,proto3" test_data:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,test_data=hasMore,proto3" test_data:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedsResponse) Reset() {
	*x = GetFeedsResponse{}
	mi := &file_api_tweet_v1_tweet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedsResponse) ProtoMessage() {}

func (x *GetFeedsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tweet_v1_tweet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedsResponse.ProtoReflect.Descriptor instead.
func (*GetFeedsResponse) Descriptor() ([]byte, []int) {
	return file_api_tweet_v1_tweet_proto_rawDescGZIP(), []int{10}
}

func (x *GetFeedsResponse) GetTweets() []*Tweet {
	if x != nil {
		return x.Tweets
	}
	return nil
}

func (x *GetFeedsResponse) GetNextCursor() uint64 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

func (x *GetFeedsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_api_tweet_v1_tweet_proto protoreflect.FileDescriptor

const file_api_tweet_v1_tweet_proto_rawDesc = "" +
	"\n" +
	"\x18api/tweet/v1/tweet.proto\x12\btweet.v1\"\xde\x02\n" +
	"\x05Tweet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"media_urls\x18\x04 \x03(\tR\tmediaUrls\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x05R\x04type\x12!\n" +
	"\fvisible_type\x18\x06 \x01(\x05R\vvisibleType\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"like_count\x18\t \x01(\x05R\tlikeCount\x12#\n" +
	"\rcomment_count\x18\n" +
	" \x01(\x05R\fcommentCount\x12\x1f\n" +
	"\vshare_count\x18\v \x01(\x05R\n" +
	"shareCount\x12\x19\n" +
	"\bis_liked\x18\f \x01(\bR\aisLiked\"f\n" +
	"\x12CreateTweetRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"media_urls\x18\x03 \x03(\tR\tmediaUrls\"<\n" +
	"\x13CreateTweetResponse\x12%\n" +
	"\x05tweet\x18\x01 \x01(\v2\x0f.tweet.v1.TweetR\x05tweet\",\n" +
	"\x0fGetTweetRequest\x12\x19\n" +
	"\btweet_id\x18\x01 \x01(\x04R\atweetId\"9\n" +
	"\x10GetTweetResponse\x12%\n" +
	"\x05tweet\x18\x01 \x01(\v2\x0f.tweet.v1.TweetR\x05tweet\"H\n" +
	"\x12DeleteTweetRequest\x12\x19\n" +
	"\btweet_id\x18\x01 \x01(\x04R\atweetId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"/\n" +
	"\x13DeleteTweetResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"_\n" +
	"\x16GetUserTimelineRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x04R\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"~\n" +
	"\x17GetUserTimelineResponse\x12'\n" +
	"\x06tweets\x18\x01 \x03(\v2\x0f.tweet.v1.TweetR\x06tweets\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\x04R\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"X\n" +
	"\x0fGetFeedsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x04R\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"w\n" +
	"\x10GetFeedsResponse\x12'\n" +
	"\x06tweets\x18\x01 \x03(\v2\x0f.tweet.v1.TweetR\x06tweets\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\x04R\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore2\x84\x03\n" +
	"\fTweetService\x12J\n" +
	"\vCreateTweet\x12\x1c.tweet.v1.CreateTweetRequest\x1a\x1d.tweet.v1.CreateTweetResponse\x12A\n" +
	"\bGetTweet\x12\x19.tweet.v1.GetTweetRequest\x1a\x1a.tweet.v1.GetTweetResponse\x12J\n" +
	"\vDeleteTweet\x12\x1c.tweet.v1.DeleteTweetRequest\x1a\x1d.tweet.v1.DeleteTweetResponse\x12V\n" +
	"\x0fGetUserTimeline\x12 .tweet.v1.GetUserTimelineRequest\x1a!.tweet.v1.GetUserTimelineResponse\x12A\n" +
	"\bGetFeeds\x12\x19.tweet.v1.GetFeedsRequest\x1a\x1a.tweet.v1.GetFeedsResponseB$Z\"twitter-clone/api/tweet/v1;tweetv1b\x06proto3"

var (
	file_api_tweet_v1_tweet_proto_rawDescOnce sync.Once
	file_api_tweet_v1_tweet_proto_rawDescData []byte
)

func file_api_tweet_v1_tweet_proto_rawDescGZIP() []byte {
	file_api_tweet_v1_tweet_proto_rawDescOnce.Do(func() {
		file_api_tweet_v1_tweet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_tweet_v1_tweet_proto_rawDesc), len(file_api_tweet_v1_tweet_proto_rawDesc)))
	})
	return file_api_tweet_v1_tweet_proto_rawDescData
}

var file_api_tweet_v1_tweet_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_tweet_v1_tweet_proto_goTypes = []any{
	(*Tweet)(nil),                   // 0: tweet.v1.Tweet
	(*CreateTweetRequest)(nil),      // 1: tweet.v1.CreateTweetRequest
	(*CreateTweetResponse)(nil),     // 2: tweet.v1.CreateTweetResponse
	(*GetTweetRequest)(nil),         // 3: tweet.v1.GetTweetRequest
	(*GetTweetResponse)(nil),        // 4: tweet.v1.GetTweetResponse
	(*DeleteTweetRequest)(nil),      // 5: tweet.v1.DeleteTweetRequest
	(*DeleteTweetResponse)(nil),     // 6: tweet.v1.DeleteTweetResponse
	(*GetUserTimelineRequest)(nil),  // 7: tweet.v1.GetUserTimelineRequest
	(*GetUserTimelineResponse)(nil), // 8: tweet.v1.GetUserTimelineResponse
	(*GetFeedsRequest)(nil),         // 9: tweet.v1.GetFeedsRequest
	(*GetFeedsResponse)(nil),        // 10: tweet.v1.GetFeedsResponse
}
var file_api_tweet_v1_tweet_proto_depIdxs = []int32{
	0,  // 0: tweet.v1.CreateTweetResponse.tweet:type_name -> tweet.v1.Tweet
	0,  // 1: tweet.v1.GetTweetResponse.tweet:type_name -> tweet.v1.Tweet
	0,  // 2: tweet.v1.GetUserTimelineResponse.tweets:type_name -> tweet.v1.Tweet
	0,  // 3: tweet.v1.GetFeedsResponse.tweets:type_name -> tweet.v1.Tweet
	1,  // 4: tweet.v1.TweetService.CreateTweet:input_type -> tweet.v1.CreateTweetRequest
	3,  // 5: tweet.v1.TweetService.GetTweet:input_type -> tweet.v1.GetTweetRequest
	5,  // 6: tweet.v1.TweetService.DeleteTweet:input_type -> tweet.v1.DeleteTweetRequest
	7,  // 7: tweet.v1.TweetService.GetUserTimeline:input_type -> tweet.v1.GetUserTimelineRequest
	9,  // 8: tweet.v1.TweetService.GetFeeds:input_type -> tweet.v1.GetFeedsRequest
	2,  // 9: tweet.v1.TweetService.CreateTweet:output_type -> tweet.v1.CreateTweetResponse
	4,  // 10: tweet.v1.TweetService.GetTweet:output_type -> tweet.v1.GetTweetResponse
	6,  // 11: tweet.v1.TweetService.DeleteTweet:output_type -> tweet.v1.DeleteTweetResponse
	8,  // 12: tweet.v1.TweetService.GetUserTimeline:output_type -> tweet.v1.GetUserTimelineResponse
	10, // 13: tweet.v1.TweetService.GetFeeds:output_type -> tweet.v1.GetFeedsResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_tweet_v1_tweet_proto_init() }
func file_api_tweet_v1_tweet_proto_init() {
	if File_api_tweet_v1_tweet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_tweet_v1_tweet_proto_rawDesc), len(file_api_tweet_v1_tweet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_tweet_v1_tweet_proto_goTypes,
		DependencyIndexes: file_api_tweet_v1_tweet_proto_depIdxs,
		MessageInfos:      file_api_tweet_v1_tweet_proto_msgTypes,
	}.Build()
	File_api_tweet_v1_tweet_proto = out.File
	file_api_tweet_v1_tweet_proto_goTypes = nil
	file_api_tweet_v1_tweet_proto_depIdxs = nil
}
