apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: tweet-service-pod-kill
  namespace: default
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      'app.kubernetes.io/name': 'tweet-service'
