// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package auth

import (
	"github.com/google/wire"
	"twitter-clone/api/user/v1"
	"twitter-clone/internal/module/auth/grpc"
)

// Injectors from wire_service.go:

func InitAuthServer(cfg *RawConsulConfig, userClient userv1.UserServiceClient) (*grpc.AuthService, error) {
	jwtConfig, err := ProvideJWTConfig(cfg)
	if err != nil {
		return nil, err
	}
	authService, err := grpc.NewAuthService(userClient, jwtConfig)
	if err != nil {
		return nil, err
	}
	return authService, nil
}

// wire_service.go:

var ProviderSet = wire.NewSet(
	ProvideJWTConfig, grpc.NewAuthService,
)
