apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rabbitmq
  labels:
    {{- include "twitter.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.rabbitmq.service.port }}
      targetPort: amqp
      protocol: TCP
      name: amqp
    - port: {{ .Values.rabbitmq.service.managementPort }}
      targetPort: management
      protocol: TCP
      name: management
  selector:
    {{- include "twitter.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
