// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0--rc1
// source: api/aiAgent/v1/aiAgent.proto

package aiAgentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AiAgentService_GetModelDetailedInformation_FullMethodName = "/aiAgent.v1.AiAgentService/getModelDetailedInformation"
	AiAgentService_GetRepositoryDialogue_FullMethodName       = "/aiAgent.v1.AiAgentService/getRepositoryDialogue"
	AiAgentService_GetDialogueDetail_FullMethodName           = "/aiAgent.v1.AiAgentService/getDialogueDetail"
	AiAgentService_AnalysisFiles_FullMethodName               = "/aiAgent.v1.AiAgentService/analysisFiles"
	AiAgentService_CallApiOfAi_FullMethodName                 = "/aiAgent.v1.AiAgentService/callApiOfAi"
	AiAgentService_ConsultContent_FullMethodName              = "/aiAgent.v1.AiAgentService/consultContent"
	AiAgentService_AssistPublishTwitter_FullMethodName        = "/aiAgent.v1.AiAgentService/assistPublishTwitter"
)

// AiAgentServiceClient is the client API for AiAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AiAgentService 智能体服务
type AiAgentServiceClient interface {
	// 获取模型初始化详细信息
	GetModelDetailedInformation(ctx context.Context, in *GetModelDetailedInformationRequest, opts ...grpc.CallOption) (*GetModelDetailedInformationResponse, error)
	// 获取历史对话列表
	GetRepositoryDialogue(ctx context.Context, in *GetRepositoryDialogueRequest, opts ...grpc.CallOption) (*GetRepositoryDialogueResponse, error)
	// 获取某个历史对话的详细消息记录
	GetDialogueDetail(ctx context.Context, in *GetDialogueDetailRequest, opts ...grpc.CallOption) (*GetDialogueDetailResponse, error)
	// 解析前端 pdf、word 和图片等文件
	AnalysisFiles(ctx context.Context, in *AnalysisFilesRequest, opts ...grpc.CallOption) (*AnalysisFilesResponse, error)
	// 模式一：直接调用 AI api 进行对话
	CallApiOfAi(ctx context.Context, in *CallApiOfAiRequest, opts ...grpc.CallOption) (*CallApiOfAiResponse, error)
	// 模式二：通过对话查询相关推文和作者
	ConsultContent(ctx context.Context, in *ConsultContentRequest, opts ...grpc.CallOption) (*ConsultContentResponse, error)
	// 模式三：通过提供写作信息协助构建推文
	AssistPublishTwitter(ctx context.Context, in *AssistPublishTwitterRequest, opts ...grpc.CallOption) (*AssistPublishTwitterResponse, error)
}

type aiAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAiAgentServiceClient(cc grpc.ClientConnInterface) AiAgentServiceClient {
	return &aiAgentServiceClient{cc}
}

func (c *aiAgentServiceClient) GetModelDetailedInformation(ctx context.Context, in *GetModelDetailedInformationRequest, opts ...grpc.CallOption) (*GetModelDetailedInformationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModelDetailedInformationResponse)
	err := c.cc.Invoke(ctx, AiAgentService_GetModelDetailedInformation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiAgentServiceClient) GetRepositoryDialogue(ctx context.Context, in *GetRepositoryDialogueRequest, opts ...grpc.CallOption) (*GetRepositoryDialogueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRepositoryDialogueResponse)
	err := c.cc.Invoke(ctx, AiAgentService_GetRepositoryDialogue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiAgentServiceClient) GetDialogueDetail(ctx context.Context, in *GetDialogueDetailRequest, opts ...grpc.CallOption) (*GetDialogueDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDialogueDetailResponse)
	err := c.cc.Invoke(ctx, AiAgentService_GetDialogueDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiAgentServiceClient) AnalysisFiles(ctx context.Context, in *AnalysisFilesRequest, opts ...grpc.CallOption) (*AnalysisFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalysisFilesResponse)
	err := c.cc.Invoke(ctx, AiAgentService_AnalysisFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiAgentServiceClient) CallApiOfAi(ctx context.Context, in *CallApiOfAiRequest, opts ...grpc.CallOption) (*CallApiOfAiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallApiOfAiResponse)
	err := c.cc.Invoke(ctx, AiAgentService_CallApiOfAi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiAgentServiceClient) ConsultContent(ctx context.Context, in *ConsultContentRequest, opts ...grpc.CallOption) (*ConsultContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsultContentResponse)
	err := c.cc.Invoke(ctx, AiAgentService_ConsultContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiAgentServiceClient) AssistPublishTwitter(ctx context.Context, in *AssistPublishTwitterRequest, opts ...grpc.CallOption) (*AssistPublishTwitterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssistPublishTwitterResponse)
	err := c.cc.Invoke(ctx, AiAgentService_AssistPublishTwitter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AiAgentServiceServer is the server API for AiAgentService service.
// All implementations must embed UnimplementedAiAgentServiceServer
// for forward compatibility.
//
// AiAgentService 智能体服务
type AiAgentServiceServer interface {
	// 获取模型初始化详细信息
	GetModelDetailedInformation(context.Context, *GetModelDetailedInformationRequest) (*GetModelDetailedInformationResponse, error)
	// 获取历史对话列表
	GetRepositoryDialogue(context.Context, *GetRepositoryDialogueRequest) (*GetRepositoryDialogueResponse, error)
	// 获取某个历史对话的详细消息记录
	GetDialogueDetail(context.Context, *GetDialogueDetailRequest) (*GetDialogueDetailResponse, error)
	// 解析前端 pdf、word 和图片等文件
	AnalysisFiles(context.Context, *AnalysisFilesRequest) (*AnalysisFilesResponse, error)
	// 模式一：直接调用 AI api 进行对话
	CallApiOfAi(context.Context, *CallApiOfAiRequest) (*CallApiOfAiResponse, error)
	// 模式二：通过对话查询相关推文和作者
	ConsultContent(context.Context, *ConsultContentRequest) (*ConsultContentResponse, error)
	// 模式三：通过提供写作信息协助构建推文
	AssistPublishTwitter(context.Context, *AssistPublishTwitterRequest) (*AssistPublishTwitterResponse, error)
	mustEmbedUnimplementedAiAgentServiceServer()
}

// UnimplementedAiAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAiAgentServiceServer struct{}

func (UnimplementedAiAgentServiceServer) GetModelDetailedInformation(context.Context, *GetModelDetailedInformationRequest) (*GetModelDetailedInformationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModelDetailedInformation not implemented")
}
func (UnimplementedAiAgentServiceServer) GetRepositoryDialogue(context.Context, *GetRepositoryDialogueRequest) (*GetRepositoryDialogueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRepositoryDialogue not implemented")
}
func (UnimplementedAiAgentServiceServer) GetDialogueDetail(context.Context, *GetDialogueDetailRequest) (*GetDialogueDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDialogueDetail not implemented")
}
func (UnimplementedAiAgentServiceServer) AnalysisFiles(context.Context, *AnalysisFilesRequest) (*AnalysisFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalysisFiles not implemented")
}
func (UnimplementedAiAgentServiceServer) CallApiOfAi(context.Context, *CallApiOfAiRequest) (*CallApiOfAiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CallApiOfAi not implemented")
}
func (UnimplementedAiAgentServiceServer) ConsultContent(context.Context, *ConsultContentRequest) (*ConsultContentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsultContent not implemented")
}
func (UnimplementedAiAgentServiceServer) AssistPublishTwitter(context.Context, *AssistPublishTwitterRequest) (*AssistPublishTwitterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssistPublishTwitter not implemented")
}
func (UnimplementedAiAgentServiceServer) mustEmbedUnimplementedAiAgentServiceServer() {}
func (UnimplementedAiAgentServiceServer) testEmbeddedByValue()                        {}

// UnsafeAiAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiAgentServiceServer will
// result in compilation errors.
type UnsafeAiAgentServiceServer interface {
	mustEmbedUnimplementedAiAgentServiceServer()
}

func RegisterAiAgentServiceServer(s grpc.ServiceRegistrar, srv AiAgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAiAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AiAgentService_ServiceDesc, srv)
}

func _AiAgentService_GetModelDetailedInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelDetailedInformationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiAgentServiceServer).GetModelDetailedInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiAgentService_GetModelDetailedInformation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiAgentServiceServer).GetModelDetailedInformation(ctx, req.(*GetModelDetailedInformationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiAgentService_GetRepositoryDialogue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRepositoryDialogueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiAgentServiceServer).GetRepositoryDialogue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiAgentService_GetRepositoryDialogue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiAgentServiceServer).GetRepositoryDialogue(ctx, req.(*GetRepositoryDialogueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiAgentService_GetDialogueDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDialogueDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiAgentServiceServer).GetDialogueDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiAgentService_GetDialogueDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiAgentServiceServer).GetDialogueDetail(ctx, req.(*GetDialogueDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiAgentService_AnalysisFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalysisFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiAgentServiceServer).AnalysisFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiAgentService_AnalysisFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiAgentServiceServer).AnalysisFiles(ctx, req.(*AnalysisFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiAgentService_CallApiOfAi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallApiOfAiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiAgentServiceServer).CallApiOfAi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiAgentService_CallApiOfAi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiAgentServiceServer).CallApiOfAi(ctx, req.(*CallApiOfAiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiAgentService_ConsultContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsultContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiAgentServiceServer).ConsultContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiAgentService_ConsultContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiAgentServiceServer).ConsultContent(ctx, req.(*ConsultContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiAgentService_AssistPublishTwitter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssistPublishTwitterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiAgentServiceServer).AssistPublishTwitter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiAgentService_AssistPublishTwitter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiAgentServiceServer).AssistPublishTwitter(ctx, req.(*AssistPublishTwitterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AiAgentService_ServiceDesc is the grpc.ServiceDesc for AiAgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AiAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aiAgent.v1.AiAgentService",
	HandlerType: (*AiAgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getModelDetailedInformation",
			Handler:    _AiAgentService_GetModelDetailedInformation_Handler,
		},
		{
			MethodName: "getRepositoryDialogue",
			Handler:    _AiAgentService_GetRepositoryDialogue_Handler,
		},
		{
			MethodName: "getDialogueDetail",
			Handler:    _AiAgentService_GetDialogueDetail_Handler,
		},
		{
			MethodName: "analysisFiles",
			Handler:    _AiAgentService_AnalysisFiles_Handler,
		},
		{
			MethodName: "callApiOfAi",
			Handler:    _AiAgentService_CallApiOfAi_Handler,
		},
		{
			MethodName: "consultContent",
			Handler:    _AiAgentService_ConsultContent_Handler,
		},
		{
			MethodName: "assistPublishTwitter",
			Handler:    _AiAgentService_AssistPublishTwitter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/aiAgent/v1/aiAgent.proto",
}
