// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0--rc1
// source: api/aiAgent/v1/aiAgent.proto

package aiAgentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 对话必备内容
type MainContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DialogueId    uint64                 `protobuf:"varint,3,opt,name=dialogue_id,json=dialogueId,proto3" json:"dialogue_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MainContent) Reset() {
	*x = MainContent{}
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MainContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MainContent) ProtoMessage() {}

func (x *MainContent) ProtoReflect() protoreflect.Message {
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MainContent.ProtoReflect.Descriptor instead.
func (*MainContent) Descriptor() ([]byte, []int) {
	return file_api_aiAgent_v1_aiAgent_proto_rawDescGZIP(), []int{0}
}

func (x *MainContent) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MainContent) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MainContent) GetDialogueId() uint64 {
	if x != nil {
		return x.DialogueId
	}
	return 0
}

func (x *MainContent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 单条历史消息记录
type RepositoryContentList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DialogueId    uint64                 `protobuf:"varint,3,opt,name=dialogue_id,json=dialogueId,proto3" json:"dialogue_id,omitempty"`
	Question      string                 `protobuf:"bytes,4,opt,name=question,proto3" json:"question,omitempty"`
	Response      string                 `protobuf:"bytes,5,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepositoryContentList) Reset() {
	*x = RepositoryContentList{}
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepositoryContentList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepositoryContentList) ProtoMessage() {}

func (x *RepositoryContentList) ProtoReflect() protoreflect.Message {
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepositoryContentList.ProtoReflect.Descriptor instead.
func (*RepositoryContentList) Descriptor() ([]byte, []int) {
	return file_api_aiAgent_v1_aiAgent_proto_rawDescGZIP(), []int{1}
}

func (x *RepositoryContentList) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RepositoryContentList) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RepositoryContentList) GetDialogueId() uint64 {
	if x != nil {
		return x.DialogueId
	}
	return 0
}

func (x *RepositoryContentList) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *RepositoryContentList) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

// 历史对话（标题级别）
type RepositoryDialogue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepositoryDialogue) Reset() {
	*x = RepositoryDialogue{}
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepositoryDialogue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepositoryDialogue) ProtoMessage() {}

func (x *RepositoryDialogue) ProtoReflect() protoreflect.Message {
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepositoryDialogue.ProtoReflect.Descriptor instead.
func (*RepositoryDialogue) Descriptor() ([]byte, []int) {
	return file_api_aiAgent_v1_aiAgent_proto_rawDescGZIP(), []int{2}
}

func (x *RepositoryDialogue) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RepositoryDialogue) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RepositoryDialogue) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

// 文件类型
type FileKind struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileKind) Reset() {
	*x = FileKind{}
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileKind) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileKind) ProtoMessage() {}

func (x *FileKind) ProtoReflect() protoreflect.Message {
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileKind.ProtoReflect.Descriptor instead.
func (*FileKind) Descriptor() ([]byte, []int) {
	return file_api_aiAgent_v1_aiAgent_proto_rawDescGZIP(), []int{3}
}

func (x *FileKind) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FileKind) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 模型信息
type ModelKind struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MaxTokens     uint32                 `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	FileKindList  []*FileKind            `protobuf:"bytes,5,rep,name=file_kind_list,json=fileKindList,proto3" json:"file_kind_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelKind) Reset() {
	*x = ModelKind{}
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelKind) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelKind) ProtoMessage() {}

func (x *ModelKind) ProtoReflect() protoreflect.Message {
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelKind.ProtoReflect.Descriptor instead.
func (*ModelKind) Descriptor() ([]byte, []int) {
	return file_api_aiAgent_v1_aiAgent_proto_rawDescGZIP(), []int{4}
}

func (x *ModelKind) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ModelKind) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelKind) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ModelKind) GetMaxTokens() uint32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *ModelKind) GetFileKindList() []*FileKind {
	if x != nil {
		return x.FileKindList
	}
	return nil
}

// Poll 投票
type Poll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TweetId       uint64                 `protobuf:"varint,2,opt,name=tweet_id,json=tweetId,proto3" json:"tweet_id,omitempty"`
	Question      string                 `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
	Options       []*PollOption          `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	EndTime       int64                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	IsExpired     bool                   `protobuf:"varint,6,opt,name=is_expired,json=isExpired,proto3" json:"is_expired,omitempty"`               // 计算字段
	IsVoted       bool                   `protobuf:"varint,7,opt,name=is_voted,json=isVoted,proto3" json:"is_voted,omitempty"`                     // 当前用户是否已投票
	VotedOptionId uint64                 `protobuf:"varint,8,opt,name=voted_option_id,json=votedOptionId,proto3" json:"voted_option_id,omitempty"` // 当前用户投的选项 ID
	TotalVotes    int32                  `protobuf:"varint,9,opt,name=total_votes,json=totalVotes,proto3" json:"total_votes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Poll) Reset() {
	*x = Poll{}
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Poll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Poll) ProtoMessage() {}

func (x *Poll) ProtoReflect() protoreflect.Message {
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Poll.ProtoReflect.Descriptor instead.
func (*Poll) Descriptor() ([]byte, []int) {
	return file_api_aiAgent_v1_aiAgent_proto_rawDescGZIP(), []int{5}
}

func (x *Poll) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Poll) GetTweetId() uint64 {
	if x != nil {
		return x.TweetId
	}
	return 0
}

func (x *Poll) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *Poll) GetOptions() []*PollOption {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Poll) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *Poll) GetIsExpired() bool {
	if x != nil {
		return x.IsExpired
	}
	return false
}

func (x *Poll) GetIsVoted() bool {
	if x != nil {
		return x.IsVoted
	}
	return false
}

func (x *Poll) GetVotedOptionId() uint64 {
	if x != nil {
		return x.VotedOptionId
	}
	return 0
}

func (x *Poll) GetTotalVotes() int32 {
	if x != nil {
		return x.TotalVotes
	}
	return 0
}

// PollOption 投票选项
type PollOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PollId        uint64                 `protobuf:"varint,2,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	VoteCount     int32                  `protobuf:"varint,4,opt,name=vote_count,json=voteCount,proto3" json:"vote_count,omitempty"`
	Percentage    float32                `protobuf:"fixed32,5,opt,name=percentage,proto3" json:"percentage,omitempty"` // 计算字段：百分比 (0-100)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollOption) Reset() {
	*x = PollOption{}
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollOption) ProtoMessage() {}

func (x *PollOption) ProtoReflect() protoreflect.Message {
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollOption.ProtoReflect.Descriptor instead.
func (*PollOption) Descriptor() ([]byte, []int) {
	return file_api_aiAgent_v1_aiAgent_proto_rawDescGZIP(), []int{6}
}

func (x *PollOption) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PollOption) GetPollId() uint64 {
	if x != nil {
		return x.PollId
	}
	return 0
}

func (x *PollOption) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PollOption) GetVoteCount() int32 {
	if x != nil {
		return x.VoteCount
	}
	return 0
}

func (x *PollOption) GetPercentage() float32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

// 推文
type Tweet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	MediaUrls     []string               `protobuf:"bytes,4,rep,name=media_urls,json=mediaUrls,proto3" json:"media_urls,omitempty"`
	Type          int32                  `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	VisibleType   int32                  `protobuf:"varint,6,opt,name=visible_type,json=visibleType,proto3" json:"visible_type,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LikeCount     int32                  `protobuf:"varint,9,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	CommentCount  int32                  `protobuf:"varint,10,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	ShareCount    int32                  `protobuf:"varint,11,opt,name=share_count,json=shareCount,proto3" json:"share_count,omitempty"`
	IsLiked       bool                   `protobuf:"varint,12,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`
	ParentId      uint64                 `protobuf:"varint,13,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Poll          *Poll                  `protobuf:"bytes,14,opt,name=poll,proto3" json:"poll,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tweet) Reset() {
	*x = Tweet{}
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tweet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tweet) ProtoMessage() {}

func (x *Tweet) ProtoReflect() protoreflect.Message {
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tweet.ProtoReflect.Descriptor instead.
func (*Tweet) Descriptor() ([]byte, []int) {
	return file_api_aiAgent_v1_aiAgent_proto_rawDescGZIP(), []int{7}
}

func (x *Tweet) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tweet) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Tweet) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Tweet) GetMediaUrls() []string {
	if x != nil {
		return x.MediaUrls
	}
	return nil
}

func (x *Tweet) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Tweet) GetVisibleType() int32 {
	if x != nil {
		return x.VisibleType
	}
	return 0
}

func (x *Tweet) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Tweet) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Tweet) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Tweet) GetCommentCount() int32 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *Tweet) GetShareCount() int32 {
	if x != nil {
		return x.ShareCount
	}
	return 0
}

func (x *Tweet) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

func (x *Tweet) GetParentId() uint64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Tweet) GetPoll() *Poll {
	if x != nil {
		return x.Poll
	}
	return nil
}

// 推文查询结果条目
type TweetResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TweetId       uint64                 `protobuf:"varint,1,opt,name=tweet_id,json=tweetId,proto3" json:"tweet_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`         // 站内访问 URL，如 /tweet/123456
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"` // AI 对这条推文的简短摘要，方便用户决定要不要点进去
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TweetResult) Reset() {
	*x = TweetResult{}
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TweetResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TweetResult) ProtoMessage() {}

func (x *TweetResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TweetResult.ProtoReflect.Descriptor instead.
func (*TweetResult) Descriptor() ([]byte, []int) {
	return file_api_aiAgent_v1_aiAgent_proto_rawDescGZIP(), []int{8}
}

func (x *TweetResult) GetTweetId() uint64 {
	if x != nil {
		return x.TweetId
	}
	return 0
}

func (x *TweetResult) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *TweetResult) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type GetModelDetailedInformationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelDetailedInformationRequest) Reset() {
	*x = GetModelDetailedInformationRequest{}
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelDetailedInformationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelDetailedInformationRequest) ProtoMessage() {}

func (x *GetModelDetailedInformationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelDetailedInformationRequest.ProtoReflect.Descriptor instead.
func (*GetModelDetailedInformationRequest) Descriptor() ([]byte, []int) {
	return file_api_aiAgent_v1_aiAgent_proto_rawDescGZIP(), []int{9}
}

func (x *GetModelDetailedInformationRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetModelDetailedInformationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint64                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	ModelKindList []*ModelKind           `protobuf:"bytes,3,rep,name=model_kind_list,json=modelKindList,proto3" json:"model_kind_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelDetailedInformationResponse) Reset() {
	*x = GetModelDetailedInformationResponse{}
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelDetailedInformationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelDetailedInformationResponse) ProtoMessage() {}

func (x *GetModelDetailedInformationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelDetailedInformationResponse.ProtoReflect.Descriptor instead.
func (*GetModelDetailedInformationResponse) Descriptor() ([]byte, []int) {
	return file_api_aiAgent_v1_aiAgent_proto_rawDescGZIP(), []int{10}
}

func (x *GetModelDetailedInformationResponse) GetCode() uint64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetModelDetailedInformationResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetModelDetailedInformationResponse) GetModelKindList() []*ModelKind {
	if x != nil {
		return x.ModelKindList
	}
	return nil
}

type GetRepositoryDialogueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepositoryDialogueRequest) Reset() {
	*x = GetRepositoryDialogueRequest{}
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepositoryDialogueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepositoryDialogueRequest) ProtoMessage() {}

func (x *GetRepositoryDialogueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepositoryDialogueRequest.ProtoReflect.Descriptor instead.
func (*GetRepositoryDialogueRequest) Descriptor() ([]byte, []int) {
	return file_api_aiAgent_v1_aiAgent_proto_rawDescGZIP(), []int{11}
}

func (x *GetRepositoryDialogueRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetRepositoryDialogueResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Code                   uint64                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                    string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	RepositoryDialogueList []*RepositoryDialogue  `protobuf:"bytes,3,rep,name=repository_dialogue_list,json=repositoryDialogueList,proto3" json:"repository_dialogue_list,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetRepositoryDialogueResponse) Reset() {
	*x = GetRepositoryDialogueResponse{}
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepositoryDialogueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepositoryDialogueResponse) ProtoMessage() {}

func (x *GetRepositoryDialogueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepositoryDialogueResponse.ProtoReflect.Descriptor instead.
func (*GetRepositoryDialogueResponse) Descriptor() ([]byte, []int) {
	return file_api_aiAgent_v1_aiAgent_proto_rawDescGZIP(), []int{12}
}

func (x *GetRepositoryDialogueResponse) GetCode() uint64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetRepositoryDialogueResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetRepositoryDialogueResponse) GetRepositoryDialogueList() []*RepositoryDialogue {
	if x != nil {
		return x.RepositoryDialogueList
	}
	return nil
}

type GetDialogueDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DialogueId    uint64                 `protobuf:"varint,2,opt,name=dialogue_id,json=dialogueId,proto3" json:"dialogue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDialogueDetailRequest) Reset() {
	*x = GetDialogueDetailRequest{}
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDialogueDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDialogueDetailRequest) ProtoMessage() {}

func (x *GetDialogueDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDialogueDetailRequest.ProtoReflect.Descriptor instead.
func (*GetDialogueDetailRequest) Descriptor() ([]byte, []int) {
	return file_api_aiAgent_v1_aiAgent_proto_rawDescGZIP(), []int{13}
}

func (x *GetDialogueDetailRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetDialogueDetailRequest) GetDialogueId() uint64 {
	if x != nil {
		return x.DialogueId
	}
	return 0
}

type GetDialogueDetailResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Code          uint64                   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Messages      []*RepositoryContentList `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDialogueDetailResponse) Reset() {
	*x = GetDialogueDetailResponse{}
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDialogueDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDialogueDetailResponse) ProtoMessage() {}

func (x *GetDialogueDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDialogueDetailResponse.ProtoReflect.Descriptor instead.
func (*GetDialogueDetailResponse) Descriptor() ([]byte, []int) {
	return file_api_aiAgent_v1_aiAgent_proto_rawDescGZIP(), []int{14}
}

func (x *GetDialogueDetailResponse) GetCode() uint64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetDialogueDetailResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetDialogueDetailResponse) GetMessages() []*RepositoryContentList {
	if x != nil {
		return x.Messages
	}
	return nil
}

type AnalysisFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileKindId    uint64                 `protobuf:"varint,2,opt,name=file_kind_id,json=fileKindId,proto3" json:"file_kind_id,omitempty"`
	FileContent   []byte                 `protobuf:"bytes,3,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisFilesRequest) Reset() {
	*x = AnalysisFilesRequest{}
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisFilesRequest) ProtoMessage() {}

func (x *AnalysisFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisFilesRequest.ProtoReflect.Descriptor instead.
func (*AnalysisFilesRequest) Descriptor() ([]byte, []int) {
	return file_api_aiAgent_v1_aiAgent_proto_rawDescGZIP(), []int{15}
}

func (x *AnalysisFilesRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AnalysisFilesRequest) GetFileKindId() uint64 {
	if x != nil {
		return x.FileKindId
	}
	return 0
}

func (x *AnalysisFilesRequest) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

type AnalysisFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint64                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	ParsedContent string                 `protobuf:"bytes,3,opt,name=parsed_content,json=parsedContent,proto3" json:"parsed_content,omitempty"` // 解析出的文本内容，供后续对话使用
	FileKey       string                 `protobuf:"bytes,4,opt,name=file_key,json=fileKey,proto3" json:"file_key,omitempty"`                   // 存储 key，后续对话可引用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisFilesResponse) Reset() {
	*x = AnalysisFilesResponse{}
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisFilesResponse) ProtoMessage() {}

func (x *AnalysisFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisFilesResponse.ProtoReflect.Descriptor instead.
func (*AnalysisFilesResponse) Descriptor() ([]byte, []int) {
	return file_api_aiAgent_v1_aiAgent_proto_rawDescGZIP(), []int{16}
}

func (x *AnalysisFilesResponse) GetCode() uint64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AnalysisFilesResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *AnalysisFilesResponse) GetParsedContent() string {
	if x != nil {
		return x.ParsedContent
	}
	return ""
}

func (x *AnalysisFilesResponse) GetFileKey() string {
	if x != nil {
		return x.FileKey
	}
	return ""
}

type CallApiOfAiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ModelKindId   uint64                 `protobuf:"varint,2,opt,name=model_kind_id,json=modelKindId,proto3" json:"model_kind_id,omitempty"`
	MainContent   *MainContent           `protobuf:"bytes,3,opt,name=main_content,json=mainContent,proto3" json:"main_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallApiOfAiRequest) Reset() {
	*x = CallApiOfAiRequest{}
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallApiOfAiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallApiOfAiRequest) ProtoMessage() {}

func (x *CallApiOfAiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallApiOfAiRequest.ProtoReflect.Descriptor instead.
func (*CallApiOfAiRequest) Descriptor() ([]byte, []int) {
	return file_api_aiAgent_v1_aiAgent_proto_rawDescGZIP(), []int{17}
}

func (x *CallApiOfAiRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CallApiOfAiRequest) GetModelKindId() uint64 {
	if x != nil {
		return x.ModelKindId
	}
	return 0
}

func (x *CallApiOfAiRequest) GetMainContent() *MainContent {
	if x != nil {
		return x.MainContent
	}
	return nil
}

type CallApiOfAiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint64                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Response      string                 `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallApiOfAiResponse) Reset() {
	*x = CallApiOfAiResponse{}
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallApiOfAiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallApiOfAiResponse) ProtoMessage() {}

func (x *CallApiOfAiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallApiOfAiResponse.ProtoReflect.Descriptor instead.
func (*CallApiOfAiResponse) Descriptor() ([]byte, []int) {
	return file_api_aiAgent_v1_aiAgent_proto_rawDescGZIP(), []int{18}
}

func (x *CallApiOfAiResponse) GetCode() uint64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CallApiOfAiResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CallApiOfAiResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type ConsultContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ModelKindId   uint64                 `protobuf:"varint,2,opt,name=model_kind_id,json=modelKindId,proto3" json:"model_kind_id,omitempty"`
	MainContent   *MainContent           `protobuf:"bytes,3,opt,name=main_content,json=mainContent,proto3" json:"main_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultContentRequest) Reset() {
	*x = ConsultContentRequest{}
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultContentRequest) ProtoMessage() {}

func (x *ConsultContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultContentRequest.ProtoReflect.Descriptor instead.
func (*ConsultContentRequest) Descriptor() ([]byte, []int) {
	return file_api_aiAgent_v1_aiAgent_proto_rawDescGZIP(), []int{19}
}

func (x *ConsultContentRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ConsultContentRequest) GetModelKindId() uint64 {
	if x != nil {
		return x.ModelKindId
	}
	return 0
}

func (x *ConsultContentRequest) GetMainContent() *MainContent {
	if x != nil {
		return x.MainContent
	}
	return nil
}

type ConsultContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint64                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Response      string                 `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`                    // AI 自然语言回复
	TweetList     []*TweetResult         `protobuf:"bytes,4,rep,name=tweet_list,json=tweetList,proto3" json:"tweet_list,omitempty"` // 推文 id + 跳转 url + 摘要
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultContentResponse) Reset() {
	*x = ConsultContentResponse{}
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultContentResponse) ProtoMessage() {}

func (x *ConsultContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultContentResponse.ProtoReflect.Descriptor instead.
func (*ConsultContentResponse) Descriptor() ([]byte, []int) {
	return file_api_aiAgent_v1_aiAgent_proto_rawDescGZIP(), []int{20}
}

func (x *ConsultContentResponse) GetCode() uint64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ConsultContentResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ConsultContentResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *ConsultContentResponse) GetTweetList() []*TweetResult {
	if x != nil {
		return x.TweetList
	}
	return nil
}

type AssistPublishTwitterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ModelKindId   uint64                 `protobuf:"varint,2,opt,name=model_kind_id,json=modelKindId,proto3" json:"model_kind_id,omitempty"`
	MainContent   *MainContent           `protobuf:"bytes,3,opt,name=main_content,json=mainContent,proto3" json:"main_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssistPublishTwitterRequest) Reset() {
	*x = AssistPublishTwitterRequest{}
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssistPublishTwitterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssistPublishTwitterRequest) ProtoMessage() {}

func (x *AssistPublishTwitterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssistPublishTwitterRequest.ProtoReflect.Descriptor instead.
func (*AssistPublishTwitterRequest) Descriptor() ([]byte, []int) {
	return file_api_aiAgent_v1_aiAgent_proto_rawDescGZIP(), []int{21}
}

func (x *AssistPublishTwitterRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AssistPublishTwitterRequest) GetModelKindId() uint64 {
	if x != nil {
		return x.ModelKindId
	}
	return 0
}

func (x *AssistPublishTwitterRequest) GetMainContent() *MainContent {
	if x != nil {
		return x.MainContent
	}
	return nil
}

type AssistPublishTwitterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint64                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Response      string                 `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`                    // AI 生成的推文草稿说明
	TweetList     []*Tweet               `protobuf:"bytes,4,rep,name=tweet_list,json=tweetList,proto3" json:"tweet_list,omitempty"` // 生成的推文候选列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssistPublishTwitterResponse) Reset() {
	*x = AssistPublishTwitterResponse{}
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssistPublishTwitterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssistPublishTwitterResponse) ProtoMessage() {}

func (x *AssistPublishTwitterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_aiAgent_v1_aiAgent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssistPublishTwitterResponse.ProtoReflect.Descriptor instead.
func (*AssistPublishTwitterResponse) Descriptor() ([]byte, []int) {
	return file_api_aiAgent_v1_aiAgent_proto_rawDescGZIP(), []int{22}
}

func (x *AssistPublishTwitterResponse) GetCode() uint64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AssistPublishTwitterResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *AssistPublishTwitterResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *AssistPublishTwitterResponse) GetTweetList() []*Tweet {
	if x != nil {
		return x.TweetList
	}
	return nil
}

var File_api_aiAgent_v1_aiAgent_proto protoreflect.FileDescriptor

const file_api_aiAgent_v1_aiAgent_proto_rawDesc = "" +
	"\n" +
	"\x1capi/aiAgent/v1/aiAgent.proto\x12\n" +
	"aiAgent.v1\"q\n" +
	"\vMainContent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x1f\n" +
	"\vdialogue_id\x18\x03 \x01(\x04R\n" +
	"dialogueId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"\x99\x01\n" +
	"\x15RepositoryContentList\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x1f\n" +
	"\vdialogue_id\x18\x03 \x01(\x04R\n" +
	"dialogueId\x12\x1a\n" +
	"\bquestion\x18\x04 \x01(\tR\bquestion\x12\x1a\n" +
	"\bresponse\x18\x05 \x01(\tR\bresponse\"S\n" +
	"\x12RepositoryDialogue\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\".\n" +
	"\bFileKind\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xac\x01\n" +
	"\tModelKind\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\rR\tmaxTokens\x12:\n" +
	"\x0efile_kind_list\x18\x05 \x03(\v2\x14.aiAgent.v1.FileKindR\ffileKindList\"\x9d\x02\n" +
	"\x04Poll\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x19\n" +
	"\btweet_id\x18\x02 \x01(\x04R\atweetId\x12\x1a\n" +
	"\bquestion\x18\x03 \x01(\tR\bquestion\x120\n" +
	"\aoptions\x18\x04 \x03(\v2\x16.aiAgent.v1.PollOptionR\aoptions\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\x12\x1d\n" +
	"\n" +
	"is_expired\x18\x06 \x01(\bR\tisExpired\x12\x19\n" +
	"\bis_voted\x18\a \x01(\bR\aisVoted\x12&\n" +
	"\x0fvoted_option_id\x18\b \x01(\x04R\rvotedOptionId\x12\x1f\n" +
	"\vtotal_votes\x18\t \x01(\x05R\n" +
	"totalVotes\"\x88\x01\n" +
	"\n" +
	"PollOption\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\apoll_id\x18\x02 \x01(\x04R\x06pollId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"vote_count\x18\x04 \x01(\x05R\tvoteCount\x12\x1e\n" +
	"\n" +
	"percentage\x18\x05 \x01(\x02R\n" +
	"percentage\"\xa1\x03\n" +
	"\x05Tweet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"media_urls\x18\x04 \x03(\tR\tmediaUrls\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x05R\x04type\x12!\n" +
	"\fvisible_type\x18\x06 \x01(\x05R\vvisibleType\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"like_count\x18\t \x01(\x05R\tlikeCount\x12#\n" +
	"\rcomment_count\x18\n" +
	" \x01(\x05R\fcommentCount\x12\x1f\n" +
	"\vshare_count\x18\v \x01(\x05R\n" +
	"shareCount\x12\x19\n" +
	"\bis_liked\x18\f \x01(\bR\aisLiked\x12\x1b\n" +
	"\tparent_id\x18\r \x01(\x04R\bparentId\x12$\n" +
	"\x04poll\x18\x0e \x01(\v2\x10.aiAgent.v1.PollR\x04poll\"T\n" +
	"\vTweetResult\x12\x19\n" +
	"\btweet_id\x18\x01 \x01(\x04R\atweetId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\"=\n" +
	"\"getModelDetailedInformationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"\x8a\x01\n" +
	"#getModelDetailedInformationResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x04R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12=\n" +
	"\x0fmodel_kind_list\x18\x03 \x03(\v2\x15.aiAgent.v1.ModelKindR\rmodelKindList\"7\n" +
	"\x1cgetRepositoryDialogueRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"\x9f\x01\n" +
	"\x1dgetRepositoryDialogueResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x04R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12X\n" +
	"\x18repository_dialogue_list\x18\x03 \x03(\v2\x1e.aiAgent.v1.RepositoryDialogueR\x16repositoryDialogueList\"T\n" +
	"\x18getDialogueDetailRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1f\n" +
	"\vdialogue_id\x18\x02 \x01(\x04R\n" +
	"dialogueId\"\x80\x01\n" +
	"\x19getDialogueDetailResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x04R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12=\n" +
	"\bmessages\x18\x03 \x03(\v2!.aiAgent.v1.RepositoryContentListR\bmessages\"t\n" +
	"\x14analysisFilesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12 \n" +
	"\ffile_kind_id\x18\x02 \x01(\x04R\n" +
	"fileKindId\x12!\n" +
	"\ffile_content\x18\x03 \x01(\fR\vfileContent\"\x7f\n" +
	"\x15analysisFilesResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x04R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12%\n" +
	"\x0eparsed_content\x18\x03 \x01(\tR\rparsedContent\x12\x19\n" +
	"\bfile_key\x18\x04 \x01(\tR\afileKey\"\x8d\x01\n" +
	"\x12callApiOfAiRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\"\n" +
	"\rmodel_kind_id\x18\x02 \x01(\x04R\vmodelKindId\x12:\n" +
	"\fmain_content\x18\x03 \x01(\v2\x17.aiAgent.v1.MainContentR\vmainContent\"W\n" +
	"\x13callApiOfAiResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x04R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1a\n" +
	"\bresponse\x18\x03 \x01(\tR\bresponse\"\x90\x01\n" +
	"\x15consultContentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\"\n" +
	"\rmodel_kind_id\x18\x02 \x01(\x04R\vmodelKindId\x12:\n" +
	"\fmain_content\x18\x03 \x01(\v2\x17.aiAgent.v1.MainContentR\vmainContent\"\x92\x01\n" +
	"\x16consultContentResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x04R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1a\n" +
	"\bresponse\x18\x03 \x01(\tR\bresponse\x126\n" +
	"\n" +
	"tweet_list\x18\x04 \x03(\v2\x17.aiAgent.v1.TweetResultR\ttweetList\"\x96\x01\n" +
	"\x1bassistPublishTwitterRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\"\n" +
	"\rmodel_kind_id\x18\x02 \x01(\x04R\vmodelKindId\x12:\n" +
	"\fmain_content\x18\x03 \x01(\v2\x17.aiAgent.v1.MainContentR\vmainContent\"\x92\x01\n" +
	"\x1cassistPublishTwitterResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x04R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1a\n" +
	"\bresponse\x18\x03 \x01(\tR\bresponse\x120\n" +
	"\n" +
	"tweet_list\x18\x04 \x03(\v2\x11.aiAgent.v1.TweetR\ttweetList2\xca\x05\n" +
	"\x0eAiAgentService\x12~\n" +
	"\x1bgetModelDetailedInformation\x12..aiAgent.v1.getModelDetailedInformationRequest\x1a/.aiAgent.v1.getModelDetailedInformationResponse\x12l\n" +
	"\x15getRepositoryDialogue\x12(.aiAgent.v1.getRepositoryDialogueRequest\x1a).aiAgent.v1.getRepositoryDialogueResponse\x12`\n" +
	"\x11getDialogueDetail\x12$.aiAgent.v1.getDialogueDetailRequest\x1a%.aiAgent.v1.getDialogueDetailResponse\x12T\n" +
	"\ranalysisFiles\x12 .aiAgent.v1.analysisFilesRequest\x1a!.aiAgent.v1.analysisFilesResponse\x12N\n" +
	"\vcallApiOfAi\x12\x1e.aiAgent.v1.callApiOfAiRequest\x1a\x1f.aiAgent.v1.callApiOfAiResponse\x12W\n" +
	"\x0econsultContent\x12!.aiAgent.v1.consultContentRequest\x1a\".aiAgent.v1.consultContentResponse\x12i\n" +
	"\x14assistPublishTwitter\x12'.aiAgent.v1.assistPublishTwitterRequest\x1a(.aiAgent.v1.assistPublishTwitterResponseB(Z&twitter-clone/api/aiAgent/v1;aiAgentv1b\x06proto3"

var (
	file_api_aiAgent_v1_aiAgent_proto_rawDescOnce sync.Once
	file_api_aiAgent_v1_aiAgent_proto_rawDescData []byte
)

func file_api_aiAgent_v1_aiAgent_proto_rawDescGZIP() []byte {
	file_api_aiAgent_v1_aiAgent_proto_rawDescOnce.Do(func() {
		file_api_aiAgent_v1_aiAgent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_aiAgent_v1_aiAgent_proto_rawDesc), len(file_api_aiAgent_v1_aiAgent_proto_rawDesc)))
	})
	return file_api_aiAgent_v1_aiAgent_proto_rawDescData
}

var file_api_aiAgent_v1_aiAgent_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_api_aiAgent_v1_aiAgent_proto_goTypes = []any{
	(*MainContent)(nil),                         // 0: aiAgent.v1.MainContent
	(*RepositoryContentList)(nil),               // 1: aiAgent.v1.RepositoryContentList
	(*RepositoryDialogue)(nil),                  // 2: aiAgent.v1.RepositoryDialogue
	(*FileKind)(nil),                            // 3: aiAgent.v1.FileKind
	(*ModelKind)(nil),                           // 4: aiAgent.v1.ModelKind
	(*Poll)(nil),                                // 5: aiAgent.v1.Poll
	(*PollOption)(nil),                          // 6: aiAgent.v1.PollOption
	(*Tweet)(nil),                               // 7: aiAgent.v1.Tweet
	(*TweetResult)(nil),                         // 8: aiAgent.v1.TweetResult
	(*GetModelDetailedInformationRequest)(nil),  // 9: aiAgent.v1.getModelDetailedInformationRequest
	(*GetModelDetailedInformationResponse)(nil), // 10: aiAgent.v1.getModelDetailedInformationResponse
	(*GetRepositoryDialogueRequest)(nil),        // 11: aiAgent.v1.getRepositoryDialogueRequest
	(*GetRepositoryDialogueResponse)(nil),       // 12: aiAgent.v1.getRepositoryDialogueResponse
	(*GetDialogueDetailRequest)(nil),            // 13: aiAgent.v1.getDialogueDetailRequest
	(*GetDialogueDetailResponse)(nil),           // 14: aiAgent.v1.getDialogueDetailResponse
	(*AnalysisFilesRequest)(nil),                // 15: aiAgent.v1.analysisFilesRequest
	(*AnalysisFilesResponse)(nil),               // 16: aiAgent.v1.analysisFilesResponse
	(*CallApiOfAiRequest)(nil),                  // 17: aiAgent.v1.callApiOfAiRequest
	(*CallApiOfAiResponse)(nil),                 // 18: aiAgent.v1.callApiOfAiResponse
	(*ConsultContentRequest)(nil),               // 19: aiAgent.v1.consultContentRequest
	(*ConsultContentResponse)(nil),              // 20: aiAgent.v1.consultContentResponse
	(*AssistPublishTwitterRequest)(nil),         // 21: aiAgent.v1.assistPublishTwitterRequest
	(*AssistPublishTwitterResponse)(nil),        // 22: aiAgent.v1.assistPublishTwitterResponse
}
var file_api_aiAgent_v1_aiAgent_proto_depIdxs = []int32{
	3,  // 0: aiAgent.v1.ModelKind.file_kind_list:type_name -> aiAgent.v1.FileKind
	6,  // 1: aiAgent.v1.Poll.options:type_name -> aiAgent.v1.PollOption
	5,  // 2: aiAgent.v1.Tweet.poll:type_name -> aiAgent.v1.Poll
	4,  // 3: aiAgent.v1.getModelDetailedInformationResponse.model_kind_list:type_name -> aiAgent.v1.ModelKind
	2,  // 4: aiAgent.v1.getRepositoryDialogueResponse.repository_dialogue_list:type_name -> aiAgent.v1.RepositoryDialogue
	1,  // 5: aiAgent.v1.getDialogueDetailResponse.messages:type_name -> aiAgent.v1.RepositoryContentList
	0,  // 6: aiAgent.v1.callApiOfAiRequest.main_content:type_name -> aiAgent.v1.MainContent
	0,  // 7: aiAgent.v1.consultContentRequest.main_content:type_name -> aiAgent.v1.MainContent
	8,  // 8: aiAgent.v1.consultContentResponse.tweet_list:type_name -> aiAgent.v1.TweetResult
	0,  // 9: aiAgent.v1.assistPublishTwitterRequest.main_content:type_name -> aiAgent.v1.MainContent
	7,  // 10: aiAgent.v1.assistPublishTwitterResponse.tweet_list:type_name -> aiAgent.v1.Tweet
	9,  // 11: aiAgent.v1.AiAgentService.getModelDetailedInformation:input_type -> aiAgent.v1.getModelDetailedInformationRequest
	11, // 12: aiAgent.v1.AiAgentService.getRepositoryDialogue:input_type -> aiAgent.v1.getRepositoryDialogueRequest
	13, // 13: aiAgent.v1.AiAgentService.getDialogueDetail:input_type -> aiAgent.v1.getDialogueDetailRequest
	15, // 14: aiAgent.v1.AiAgentService.analysisFiles:input_type -> aiAgent.v1.analysisFilesRequest
	17, // 15: aiAgent.v1.AiAgentService.callApiOfAi:input_type -> aiAgent.v1.callApiOfAiRequest
	19, // 16: aiAgent.v1.AiAgentService.consultContent:input_type -> aiAgent.v1.consultContentRequest
	21, // 17: aiAgent.v1.AiAgentService.assistPublishTwitter:input_type -> aiAgent.v1.assistPublishTwitterRequest
	10, // 18: aiAgent.v1.AiAgentService.getModelDetailedInformation:output_type -> aiAgent.v1.getModelDetailedInformationResponse
	12, // 19: aiAgent.v1.AiAgentService.getRepositoryDialogue:output_type -> aiAgent.v1.getRepositoryDialogueResponse
	14, // 20: aiAgent.v1.AiAgentService.getDialogueDetail:output_type -> aiAgent.v1.getDialogueDetailResponse
	16, // 21: aiAgent.v1.AiAgentService.analysisFiles:output_type -> aiAgent.v1.analysisFilesResponse
	18, // 22: aiAgent.v1.AiAgentService.callApiOfAi:output_type -> aiAgent.v1.callApiOfAiResponse
	20, // 23: aiAgent.v1.AiAgentService.consultContent:output_type -> aiAgent.v1.consultContentResponse
	22, // 24: aiAgent.v1.AiAgentService.assistPublishTwitter:output_type -> aiAgent.v1.assistPublishTwitterResponse
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_aiAgent_v1_aiAgent_proto_init() }
func file_api_aiAgent_v1_aiAgent_proto_init() {
	if File_api_aiAgent_v1_aiAgent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_aiAgent_v1_aiAgent_proto_rawDesc), len(file_api_aiAgent_v1_aiAgent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_aiAgent_v1_aiAgent_proto_goTypes,
		DependencyIndexes: file_api_aiAgent_v1_aiAgent_proto_depIdxs,
		MessageInfos:      file_api_aiAgent_v1_aiAgent_proto_msgTypes,
	}.Build()
	File_api_aiAgent_v1_aiAgent_proto = out.File
	file_api_aiAgent_v1_aiAgent_proto_goTypes = nil
	file_api_aiAgent_v1_aiAgent_proto_depIdxs = nil
}
