server {
    listen 5556;
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;  # 处理前端路由
    }
    location /api/ {
        proxy_pass http://gateway:9638;    # 接口请求转发到网关
    }
}